apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tasteless-meerkat-java-springboot
  janus-idp.io/tekton: tasteless-meerkat-java-springboot
  backstage.io/kubernetes-id: tasteless-meerkat-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tasteless-meerkat-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
